import { Inter } from "next/font/google";
import { Providers } from "../../lib/providers";
import { ToastContainer } from "react-toastify";
import Footer from "./_components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundColor: "#093545",
          height: "100%",
        }}
      >
        <Providers>{children}</Providers>
        <ToastContainer />
        <Footer />
      </body>
    </html>
  );
}
