import { Inter } from "next/font/google";
import { Providers } from "../../lib/providers";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          justifyContent: "Bottom",
          backgroundColor: "#093545",
          // backgroundImage: 'url("/bgImg.png")',
          // maxWidth: "100vw",
          // overflowX: "hidden",
          height: "100%",
        }}
      >
        <Providers>{children}</Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
